---
- name: Apply Terraform (AWS)
  cloud.terraform.terraform:
    project_path: "{{ terraform_aws_project_path }}"
    state: present
    force_init: true
    variables:
      ssh_public_key: "{{ ssh_public_key }}"
      client_instance_type: "{{ aws_client_instance_type | default('c7i.large') }}"
      server_instance_type: "{{ aws_server_instance_type | default('c7i.large') }}"
      aws_region: "{{ aws_region | default('eu-west-1') }}"
      ami_id: "{{ aws_ami_id | default('') }}"

- name: Read Terraform outputs (AWS)
  cloud.terraform.terraform_output:
    project_path: "{{ terraform_aws_project_path }}"
  register: tf_aws_out

- name: Show Terraform outputs
  ansible.builtin.debug:
    var: tf_aws_out.outputs
