---
- name: Apply Terraform (libvirt)
  cloud.terraform.terraform:
    project_path: "{{ terraform_libvirt_project_path }}"
    state: present
    force_init: true
    variables:
      ssh_public_key: "{{ ssh_public_key }}"

- name: Read Terraform outputs (libvirt)
  cloud.terraform.terraform_output:
    project_path: "{{ terraform_libvirt_project_path }}"
  register: tf_libvirt_out

- name: Show Terraform outputs
  ansible.builtin.debug:
    var: tf_libvirt_out.outputs
